import Head from 'next/head'
import PostList from '../Components/PostList'
import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  return (   
    <div>
      <Head>
        <title>Blog by Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList posts={posts}/>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("/api/blogs", {headers:{Authorization: `bearer 6c7ca5913ea8b7089b7fa51f8d1cc1a359e5d61da837fa571b76e18dd757bd54c9aebc4f58a0e338d182732ee51439534e8c86cbbd087ecf4542b65229cc58ea8ee12ee9d1ccf59d23e069228754b85ada1f252aadf396b203602bf46249fd71ba0fbf711c1dc4420d305fa22c18f239c44e4541be11163c99210cf600ee2d86`}});
  const posts = await res.json();
  return {
    props: {
      posts,
    },
  };
};